rename blow2.mcfunction blow_xy2.mcfunction
rename blow2_0.mcfunction blow_xy2_0.mcfunction
rename blow2_1.mcfunction blow_xy2_1.mcfunction
rename blow2_10.mcfunction blow_xy2_10.mcfunction
rename blow2_11.mcfunction blow_xy2_11.mcfunction
rename blow2_12.mcfunction blow_xy2_12.mcfunction
rename blow2_13.mcfunction blow_xy2_13.mcfunction
rename blow2_14.mcfunction blow_xy2_14.mcfunction
rename blow2_15.mcfunction blow_xy2_15.mcfunction
rename blow2_2.mcfunction blow_xy2_2.mcfunction
rename blow2_3.mcfunction blow_xy2_3.mcfunction
rename blow2_4.mcfunction blow_xy2_4.mcfunction
rename blow2_5.mcfunction blow_xy2_5.mcfunction
rename blow2_6.mcfunction blow_xy2_6.mcfunction
rename blow2_7.mcfunction blow_xy2_7.mcfunction
rename blow2_8.mcfunction blow_xy2_8.mcfunction
rename blow2_9.mcfunction blow_xy2_9.mcfunction
rename blow2_dirt.mcfunction blow_xy2_dirt.mcfunction
rename blow2_glass.mcfunction blow_xy2_glass.mcfunction
rename blow2_glowstone.mcfunction blow_xy2_glowstone.mcfunction
rename blow2_gold_block.mcfunction blow_xy2_gold_block.mcfunction
rename blow2_gravel.mcfunction blow_xy2_gravel.mcfunction
rename blow2_lit_pumpkin.mcfunction blow_xy2_lit_pumpkin.mcfunction
rename blow2_quartz_block.mcfunction blow_xy2_quartz_block.mcfunction
rename blow2_stained_glass_0.mcfunction blow_xy2_stained_glass_0.mcfunction
rename blow2_stained_glass_14.mcfunction blow_xy2_stained_glass_14.mcfunction
rename blow2_stained_glass_15.mcfunction blow_xy2_stained_glass_15.mcfunction
rename blow2_stained_glass_4.mcfunction blow_xy2_stained_glass_4.mcfunction
rename blow2_stained_glass_5.mcfunction blow_xy2_stained_glass_5.mcfunction
rename blow2_stone0.mcfunction blow_xy2_stone0.mcfunction
rename blow2_stone1.mcfunction blow_xy2_stone1.mcfunction
rename blow2_stone3.mcfunction blow_xy2_stone3.mcfunction
rename blow2_stone5.mcfunction blow_xy2_stone5.mcfunction
rename blow_up.mcfunction blow_xy_up.mcfunction
rename blow_up_more.mcfunction blow_xy_up_more.mcfunction




































